export default {
  ACCESS_FIELD_REQUIRED: 'access field is required as boolean',
  ROLE_NOT_SUFFICIENT:
    'You required a higher access level to utilize this resource',
  SUCCESS_RESPONSE: 'Request was successfully processed',
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
  INVALID_PERMISSION:
    'Permission denied. Current user does not have the required permission to access this resource.',
  INVALID_CREDENTIALS: 'Invalid email/password',
  ACCESS_REVOKED: 'Your access has been revoked',
  EMAIL_CONFLICT: 'A user with your email already exists',
  AUTH_REQUIRED: 'Access denied,a valid access token is required',
  HMAC_VALIDATION_FAILED: 'We cannot confirm this request is from shopify',
  WELCOME: 'Thanks for dropping by, you are at Jetti app',
  DB_ERROR: 'A database error occurred, either in redis or postgres',
  MODULE_ERROR: 'A module error occurred',
  INVALID_ROLE_PARAMETER: 'Invalid role value',
  JETT_RUNNING: 'Jett is running on PORT',
  SALE_INFORMATION_ERROR: 'Error Fetching sales proper',
  FETCH_SALE_ITEM_PRICE: 'Successfully fetched sale item price',
  FETCH_SALE_ITEM_PRICE_FAILED: 'failed to fetch sale item price ',
  SUBMITTED_VENDOR_ORDER: 'Submitted vendor order successfully',
  FAILED_VENDOR_ORDER: 'Failed to Submit vendor order',
};
