export default {
  ACCESS_FIELD_REQUIRED: 'access field is required as boolean',
  ROLE_NOT_SUFFICIENT:
    'You required a higher access level to utilize this resource',
  SUCCESS_RESPONSE: 'Request was successfully processed',
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
  INVALID_PERMISSION:
    'Permission denied. Current user does not have the required permission to access this resource.',
  INVALID_CREDENTIALS: 'Invalid email/password',
  ACCESS_REVOKED: 'Your access has been revoked',
  EMAIL_CONFLICT: 'A user with your email already exists',
  AUTH_REQUIRED: 'Access denied,a valid access token is required',
  HMAC_VALIDATION_FAILED: 'We cannot confirm this request is from shopify',
  WELCOME: 'Thanks for dropping by, you are at Jetti app',
  DB_ERROR: 'A database error occurred, either in redis or postgres',
  MODULE_ERROR: 'A module error occurred',
  INVALID_ROLE_PARAMETER: 'Invalid role value',
  MOCK_PREMIER_LEAGUE_RUNNING: 'Mock premier league app is running on PORT',
  SALE_INFORMATION_ERROR: 'Error Fetching sales proper',
  FETCH_SALE_ITEM_PRICE: 'Successfully fetched sale item price',
  FETCH_SALE_ITEM_PRICE_FAILED: 'failed to fetch sale item price ',
  SUBMITTED_VENDOR_ORDER: 'Submitted vendor order successfully',
  FAILED_VENDOR_ORDER: 'Failed to Submit vendor order',
  EMAIL_EXIST_VERIFICATION_FAIL_MSG: 'Error verifying existence of user, try again.',
  REDIS_RUNNING: 'Redis server is running',
  SUCCESS: 'success',
  LOGIN_USER_SUCCESSFULLY: 'login successful',
  LOGIN_USER_FAILED: 'Error login user in',
  CREATE_USER_SUCCESSFULLY: 'Successfully registered user',
  CREATE_USER_FAILED: 'Error registering user',
  USER_EMAIL_EXIST_VERIFICATION_FAIL_MSG: 'Error verifying existence of staff, try again.',
  SUCCESSFULLY_ADDED_TEAM: 'Team added successfully',
  ERROR_CREATING_TEAM: 'Error adding to team',
  ERROR_REMOVING_TEAM: 'Error removing to team',
  SUCCESSFULLY_REMOVED_TEAM: 'Successfully removed team',
  ERROR_EDITING_TEAM: 'Error editing team',
  TEAM_DOES_NOT_EXIST: 'Team does not exist',
  ERROR_FETCHING_TEAM: ' Error fetching Team',
  ERROR_FETCHING_PAGE_TEAM: 'Could not fetch teams for that page',
  SUCCESSFULLY_FETCHED_ALL_TEAM: 'Successfully fetched all teams',
  CANNOT_PERFORM_SEARCH: 'Could not search for the team',
  DUPLICATE_TEAM_NAME: 'Duplicate team name',
  SUCCESSFULLY_UPDATED_TEAM: 'Successfully updated team',
  DUPLICATE_FIXTURE_NAME: 'Duplicate fixtures',
  SUCCESSFULLY_ADDED_FIXTURE: 'Successfully created fixtures',
  ERROR_ADDING_FEATURES: 'Error adding features',
  INVALID_FIXTURE: 'Fixture does not exist',
  ERROR_DELETING_FIXTURE: 'Error deleting fixture',
  SUCCESSFULLY_DELETED_FIXTURE: 'Successfully deleted fixture',
  ERROR_UPDATING_FIXTURES: 'Error updating fixtures',
  SUCCESSFULLY_UPDATED_FIXTURES: 'Successfully updated fixtures',
  SUCCESSFULLY_FETCHED_FIXTURE: 'Successfully fetched fixture',
  SUCCESSFULLY_FETCHED_TEAM: 'Successfully fetched team',
  SUCCESSFULLY_FETCHED_FIXTURES: 'Successfully all fixtures',
  ERROR_FETCHING_FIXTURE: 'Error fetching fixture',
  ERROR_FETCHING_FIXTURES: 'Error fetching all fixture',
  ERROR_FETCHING_PENDING_FIXTURES: 'Error fetching pending fixture'

};
